### ISSUE TITLE
config: automatic setting of SERVER_HOSTNAME (and rename)

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-rdm#111]
### Set ``SERVER_HOSTNAME`` atuomatically

When running ``invenio-cli containerize --pre`` you have to manually configure ``SERVER_HOSTNAME`` to remove the port 5000. Similar if you run locally with a different port ``invenio-cli run --port 1234`` you need to update the ``SERVER_HOSTNAME``.

It would be nice if we could find a reliable way to correctly set the server hostname.

### Rename ``SERVER_HOSTNAME`` to ``HOSTNAME``

``SERVER_HOSTNAME`` (Invenio variable) is very easily confused with ``SERVER_NAME`` (Flask variable). They have very different meaning, and thus should be renamed so they don't get confused.

I propose to rename to ``HOSTNAME`` or ``SITE_HOSTNAME``

**Comment by ppanero** [comment]
This issue expands to three repositories:

**invenio-records-resources:**
- Change variable name: https://github.com/inveniosoftware/invenio-records-resources/blob/3b5dbed63e34aad212e6c6d8c9d1f52d8e583931/invenio_records_resources/config.py#L18
- Allow it to be setdefault: https://github.com/inveniosoftware/invenio-records-resources/blob/3b5dbed63e34aad212e6c6d8c9d1f52d8e583931/invenio_records_resources/ext.py#L32
- Change the usage: https://github.com/inveniosoftware/invenio-records-resources/blob/17e0fa85b9b217c716b804ebafd74c859bdacc0b/invenio_records_resources/services/records/results.py#L23

**cookiecutter-invenio-rdm:**
- Change variable name in default `invenio.cfg`: https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/dc9796fe84fb7d2cdc88a164d964c1bbca7c25f0/%7B%7Bcookiecutter.project_shortname%7D%7D/invenio.cfg#L138

**invenio-cli:**
- Set the environment var with the `--port` and `--host` values: https://github.com/inveniosoftware/invenio-cli/blob/2bf6547b9fcaa9d9e0fa0c704b29c42ad3f14a53/invenio_cli/helpers/commands.py#L251

**Comment by ppanero** [comment]
Closed by 3 PRs, in order of need:

- https://github.com/inveniosoftware/invenio-records-resources/pull/137
- https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/117 (requires a release and version bump of the previous)
- https://github.com/inveniosoftware/invenio-cli/pull/168 (requires a release and version bump of the first)
