### ISSUE TITLE
docker: add haproxy, kibana and flower

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/cookiecutter-invenio-rdm#126]
## Is your feature request related to a problem? Please describe.
It is needed to paint a closer to reality picture when booting up a fully containerized version.

## Describe the solution you'd like
Add HAProxy, Flower, Kibana. Take `cookiecutter-invenio-instance` as reference.

## Additional context
Some where removed here https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/124 due to lack of use.

**Comment by lnielsen** [comment]
HAProxy:

- [docker-compose.yml](https://github.com/inveniosoftware/cookiecutter-invenio-instance/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/docker-services.yml#L26-L33)
- [config](https://github.com/inveniosoftware/cookiecutter-invenio-instance/tree/master/%7B%7Bcookiecutter.project_shortname%7D%7D/docker/haproxy)

[Flower and Kibana](https://github.com/inveniosoftware/cookiecutter-invenio-instance/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/docker-services.yml#L95-L110)
