### ISSUE TITLE
investigate: rabbitmq image needs update?

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/cookiecutter-invenio-rdm#127]
Package version (if known): october release

## Describe the bug

From astrowq:

>I got an error while trying to run an Invenio RDM instance:

>ERROR: for invenio-rdm-demo_mq_1  Cannot start service mq: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown

>Aftering investigating and looking up for quite some time, I found it was caused by the image used here i.e. rabbitmq:3-management. It is having a bug in it and the above error went away if I chose to use another tag e.g. rabbitmq:3.8-management

Investigate if this was a one time occurrence or if the rabbitmq image needs to be updated.

**Comment by lnielsen** [comment]
Tasks for February iteration:
- Upgrade [image](https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/docker-services.yml#L61) to ``3.8-management``

**Comment by avivace** [comment]
Looks like there are no breaking changes: https://www.rabbitmq.com/changelog.html
