### ISSUE TITLE
Add SQLite configurations or remove it as an option

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/cookiecutter-invenio-rdm#16]
As a hoster installing InvenioRDM, I am given the option to choose sqlite as a database, but none of the configuration is done when I do so.

There should be sqlite configuration in:

- https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/docker-services.yml
- https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/invenio.cfg

Or we could remove it as an option altogether.

**Comment by lnielsen** [comment]
Remove SQLite option
