### ISSUE TITLE
data: add demo subjects

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/cookiecutter-invenio-rdm#168]
Subjects vocabulary are quite instance specific. However, as an example (and to facilite it's customization), we can create a demo one (e.g. `science`: cosmology, astronomy, biology...)

**Comment by ppanero** [comment]
blocked until https://github.com/inveniosoftware/invenio-rdm-records/pull/653 is merged and released

**Comment by ppanero** [comment]
blocked in favour of https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/171 use this PR content only in case of tests....

**Comment by ppanero** [comment]
@ntarocco @lnielsen shall we close this one (along with the PR)?

**Comment by ntarocco** [comment]
I would close the issue, I am adding a comment in the PR.
