### ISSUE TITLE
cookiecutter: disable mysql as a database option

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-rdm#176]
We should disable the option to select myssql as it's untested and doesn't work with latest v8

```
You've downloaded /Users/lnielsen/.cookiecutters/cookiecutter-invenio-rdm before. Is it okay to delete and re-download it? [yes]: yes
....
Select database:
1 - postgresql
2 - mysql
Choose from 1, 2 [1]:
Select elasticsearch:
```

**Comment by fenekku** [comment]
I placed it in "Must have" because of what you said @lnielsen : it's one of those things that aren't quite working and we shouldn't support it in the LTS.
