### ISSUE TITLE
cookiecutter: add translations mechanism

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/cookiecutter-invenio-rdm#241]
- [x] `translations` folder should be in top level
- [x] invenio-cli should copy over the translations folder to `var/instance` folder so that the translations take precedence

# Bonus

Once tha above is working, invenio-cli should be able to extract_messages, compile_catalog, init_catalog, update_catalog from/to this folder.

**Goal** is to be able to extract messages both from invenio.cfg, templates and the `site` folder if the user has code defined there

## Resources

Invenio-i18n translation loading https://github.com/inveniosoftware/invenio-i18n/blob/master/invenio_i18n/ext.py#L113

**Comment by ppanero** [comment]
Notes:

- It is working manually
- Implement commands via cli: Do we want a cli in i18n or just in invenio-cli? speed vs consistency.
    - Template the commands (mainly `extract`) with the values from cookiecutter `init` (copyright holder, email, etc.).
- Should the `translations` folder be optional?
