### ISSUE TITLE
10.1 is not support by invenio-cli

### ISSUE THREAD

**Issue by superstar54** [inveniosoftware/cookiecutter-invenio-rdm#256]
## Is your feature request related to a problem? Please describe.

The latest version 10.1 is not supported.

``` console
invenio-cli init rdm -c v10.1
```
I got:
```
The v10.1 branch of repository https://github.com/inveniosoftware/cookiecutter-invenio-rdm.git could not found, have you made a typo?
```

**Comment by ppanero** [comment]
The branch has been created: https://github.com/inveniosoftware/cookiecutter-invenio-rdm/commits/v10.1

**Comment by ppanero** [comment]
Deployed locally, tested common user flows: search and record creation with files.
