### ISSUE TITLE
Remove quotes from project_shortname

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/cookiecutter-invenio-rdm#45]
Passing: "Pablo's Version" as `project_name`, results in `pablo's-version` as `project_shortname`, but it should result in `pablos-version`

**Comment by ppanero** [comment]
Basically we should sanitize the input? That's more a base cookiecutter thing rather than here. We have no control over it once we call the cookiecutter.

**Comment by fenekku** [comment]
This is what needs to be changed: https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/master/cookiecutter.json#L3
