### ISSUE TITLE
remove `unsafe_eval` from CSP policies

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/cookiecutter-invenio-rdm#47]
We should investigate how to fix the webpack configuration so it doesn't break on runtime because of string evaluation to javascript. 

**Update 20/7/2021 (from Lars)**:
- Review the CSP to see of follow lines can be removed:

```
'fonts.googleapis.com',  # for fonts
            '*.gstatic.com',    # for fonts
```

**Comment by fenekku** [comment]
To reproduce, one would remove `"'unsafe-eval'"` from the csp config and re-run `invenio-cli update`, correct? And something should break?

**Comment by zzacharo** [comment]
Yes, you would see that there is an error in console at the point that webpack is injecting a script tag to include the react application. You will see that the application is never rendered!

**Comment by fenekku** [comment]
I was able to reproduce but unfortunately spent the afternoon on this and got nowhere slowly. This thread: https://github.com/webpack/webpack/issues/5627 seemed to be about this, but a better knowledge of webpack than I have is needed to understand what they are talking about.

good luck!
