### ISSUE TITLE
Unable to create bucket using scripts/setup

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/cookiecutter-invenio-rdm#53]
Unfortunately `minio/minio` doesn't have the `mc` CLI installed on it making this line from the setup file fail https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/master/scripts/setup#L30

I don't have the perfect solution, but this worked for me.

I have created my own image for the `S3` service with the following `docker/minio/Dockerfile`
```
FROM minio/minio

RUN wget https://dl.min.io/client/mc/release/linux-amd64/mc -P /usr/bin \
    && chmod +x /usr/bin/mc

COPY ./create-bucket.sh .
```
The content of `docker/minio/create-bucket.sh`
```
#!/usr/bin/env sh

# Configure minio client to point to localhost

mc config host add local http://localhost:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}

# Delete the bucket in case it exists, start from scratch
if mc ls local | grep -q default-bucket; then
    mc rb local/default-bucket
fi

# Create the bucket
mc mb local/default-bucket
```
(NOTE: there is no `bash`, just `sh`)

the rest should remain the same besides the call inside `scripts/setup`
```
docker-compose exec s3 sh -c './create-bucket.sh'
```

---

Other solutions, that I can think of, range from adding a new "service" to the `docker-service.yml` file pulling from the `minio/mc` image;

```
mc:
    image: minio/mc
    link:
      - s3
    environment:
      MINIO_ACCESS_KEY: CHANGE_ME
      MINIO_SECRET_KEY: CHANGE_M
```

to tell the user to install and configure the `mc` locally, [documentation](https://docs.min.io/docs/minio-client-quickstart-guide.html)

I'd love to hear your thoughts on this, and if you think what I did is "good enough", I'm happy to make a PR anytime 😇

**Comment by ppanero** [comment]
Hello @egabancho Thanks for reporting!

Since we are using minio just for "demo" purposes. Meaning, it's not meant for production and it is just there to allow the user to test with S3 I would personally go with building a new docker image with `mc` installed in it. We already do something similar with Nginx.

@fenekku @zzacharo what are your thoughts?

**Comment by zzacharo** [comment]
I think that `mc` would be quite useful to be included inside a docker image for people to be able to play around with the S3 installation!

**Comment by fenekku** [comment]
+1 on having an image with `mc` ready to go.

**Comment by egabancho** [comment]
Hey guys, sorry for not doing anything here for a while. The other I realized that if we simply create a folder and point the min.io server to it it'll create a bucket automagically.

For example, min.io is started with a volume `data:/data`, if we simply create a local folder `data/default-bucket` it'll pick it up and we don't need to do anything special.

WDYT?

**Comment by ppanero** [comment]
@egabancho sounds good to me, minio is just for "demo" purposes in local... so I would say yes! thanks for checking!
