### ISSUE TITLE
docker: unable to run UI with bare built image

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/cookiecutter-invenio-rdm#54]
Since the docker image does not collect and build the assets it fails due to the lack of `manifest.json`.

Use case: As a RDM user I want to `init` my instance, build and push to my registry. Then I want to deploy it in my cloud (OpenShift, GCloud, etc.).

*Note that this proposal is an overkill*

``` dockerfile
FROM inveniosoftware/centos7-python:3.6

COPY Pipfile Pipfile.lock ./
RUN pipenv install --deploy --system

COPY ./docker/uwsgi/ ${INVENIO_INSTANCE_PATH}
COPY ./invenio.cfg ${INVENIO_INSTANCE_PATH}
COPY ./templates/ ${INVENIO_INSTANCE_PATH}/templates/
COPY ./static/ ${INVENIO_INSTANCE_PATH}/static/
COPY ./assets/ ${INVENIO_INSTANCE_PATH}/assets/
COPY ./ .

RUN invenio collect --verbose  && \
    invenio webpack create && \
    # --unsafe needed because we are running as root
    invenio webpack install --unsafe && \
    invenio webpack build

ENTRYPOINT [ "bash", "-c"]
```

This would fix but:
- Copies many files twice
- Collects and builds twice

Both of them because `containerize` does the same afterwards.

Extra: This could be an opportunity to make the image lighter and instead of `COPY`, just `MOVE` stuff around from `.` to the `INVENIO_INSTANCE_PATH`.

**Comment by fenekku** [comment]
Right, this will double webpack commands which are among our slowest...

The other weirdness is: volumes. An image is self contained (no volumes). An orchestrated deployment (like docker-compose) uses external volumes. In fact, it uses a volume for the statics/assets i.e. where these files should be created. For me it became too messy to understand where the files were residing / how they were transferred between container and volume and what happened on rebuilds ...

**Comment by ppanero** [comment]
@fenekku the problem is that the building commands are supposed to be executed before, when creating the image. Now the steps are:

1. Create the image
2. Lunch (i.e. `--containerize`)
3. `webpack build & co`

The flow to deploy would be:

1. Create an image (`docker build`)
2. Upload the image somewhere (dockerhub, GH registry)
3. Pull it in the deployment

Since the `docker build` does not include the wbepack creation, those files are nowhere in the "cloud" deployment (e.g. the helm ones). Because this ones do not follow the `--containerize`, since it only needs the app container. Therefore UI is never built.

What about:

1- Building all in the docker file
2- Making the 2nd build in containerize optional?

I fully agree with your point, but we have to find a solution, because as it is now, it is not possible to do a cloud deployment, it simply fails :(

**Comment by fenekku** [comment]
Let's think about this...(free flowing thoughts here...) Our main problem is what to do with assets/statics: do we bundle them together in the image or do we find another means?

**Bundling statics/assets together with the image**
- ultimately places the statics on each application container (web-api, web-ui, web-worker)
  * only the nginx container needs them though
- `containerize` will be slower as it would need to re run all webpack commands everytime (no ability to skip -- *might* be able to overcome this with additional code...) 
- **how does the nginx container gain access to statics?** (this is the most important issue I think) 
  * There needs to be some sort of shared volume and so mounting to a volume.
  * can helm/kubernetes do that for us?
  * can helm/kubernetes navigate subsequent deployment correctly? See "mounting in docker volumes below"  

**mounting volumes in docker**
|                          | Image     | Volume    |
|--------------------------|-----------|-----------|
| Initial                  | /staticsA | empty     |
| Mount (initial deploy)                    | /staticsA | /staticsA |
| Image update and remount (subsequent deploy) | /staticsB | :warning: /staticsA |

So the easiest solution seems to be destroying the statics/assets volume everytime, which is obviously annoying and time consuming.

But overall, deployments is what I know the least about: if there are solutions to all these problems, I am all for them.

**Comment by ppanero** [comment]
I agree with your thoughts. However, so far we have not used nginx to serve statics, since it is not specified in the conf file. So in the end... we have survived by forwarding to the web nodes so far. Lets discuss more IRL.

**Comment by fenekku** [comment]
As discussed IVL (in video life... I am sure it will catch on!) we will need to investigate this one even more (nginx config was hidden somewhere...).

**Comment by ppanero** [comment]
The possible methods (that I found, Im open to hear more) to fix this problem are:

**Method 1: flag the docker build and lunch a job**

Since we do not want to incur into the "double building" of assets
(Once in the docker build, a second if updating). One option could
be to flag the building of assets in the Dockerfile (e.g. build only
if `BUILD_ASSETS` env var is True or is set).

Then once the container is deployed (e.g. in OpenShift/Kubernetes),
a job is launched to copy/replace those assets to the shared volume (nginx
and web pod).

caveat: it might serve old assets for a bit. The job needs to be lunched by
the user, the is no "trigger".

**Method 2: build with a job after deploying**

The build of the assets does not happend on docker build time.
Once deployed a job is lunched to do so.

caveat: The build might take more time, therefore it will serve
old assets for longer. The job needs to be lunched by the user, the
is no "trigger".

**Method 3: Ask the user to build those after deploying**

The same as before, but asking the user to connect to a pod and
execute the commands as it would do for DB/ES setup.

**Method 4: link statics to nginx docker image**

In the same fashion than [ILS](https://gitlab.cern.ch/AIGROUP-cds-admin/cds-books-openshift/blob/master/docker/ui/Dockerfile)
use multi-stage docker builds and add the assets into the nginx container.
This way there is no old assets being served.

caveat: it requires pushing the nginx image each time a new version is up
and rolling deploy it.

**Method 5: init container**

OpenShift allows the use of `initContainers`. These are lightweight containers
that are lunched before every pod. They are meant to run "setup" operations.
One initContainer could be lunched to build the assets.

caveat: thi will be rebuilt every time a pod is up (e.g. autoscale, rolling
deployment...). Unless somehow an env var can tell if it has been built (this
would not work for rolling deployments).

**Method 6: serve from the web app**

This is clearly not acceptable. Just here for completenes :joy:
