### ISSUE TITLE
assets/templates: folders should be namespaced

### ISSUE THREAD

**Issue by slint** [inveniosoftware/cookiecutter-invenio-rdm#82]
- `assets/less/{{ project_name }}/theme.config`
- `templates/{{ project_name }}/`

**Comment by ppanero** [comment]
@slint This is already solved, right? By namespacing you meant with package name? Or did you meant to create the bootstrap namespace so the user can choose?
![Screenshot 2020-12-02 at 09 38 44](https://user-images.githubusercontent.com/6756943/100848978-2d940400-3482-11eb-913f-818436b0d38b.png)

**Comment by slint** [comment]
I think I also had in mind the following:

- `assets/{{ cookiecutter.package_name }}/`
- `templates/{{ cookiecutter.package_name }}/`

The reason is that maybe you want to still use the `semantic-ui` theme, but want to override even further things on your overlay... So then you would have a `APP_THEME = ['{{ cookiecutter.package_name }}', 'semantic-ui']` config

**Comment by ppanero** [comment]
After talk IRL, it is ok as is.
