### ISSUE TITLE
Double-check uwsgi ini files

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/cookiecutter-invenio-rdm#9]
uwsgi ini is tricky to get right. Double-check if merged configuration works well at Northwestern University. If not, contribute back Northwestern configurations.

**Comment by ppanero** [comment]
This issue has also more info about it: https://github.com/inveniosoftware/troubleshooting/issues/51

**Comment by fenekku** [comment]
Double-checked. The latest works for us. Closing.
